version: "3"
services:
  nopcommerce:
    image: abdelnaby1/selenium-test-script/nopcommerce
    environment:
      - BROWSER=${BROWSER}
      - HUB_HOST=hub
      - THREAD_COUNT=4
      - TEST_SUITE=nopcommerce.xml
    volumes:
      - ./output/nopcommerce:/home/selenium-docker/test-output
